# Let's Encrypt ClusterIssuers with Gateway API support
# This configuration worked perfectly on August 13, 2025

---
# Staging ClusterIssuer (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email for notifications
    email: ops@flow.swiss
    
    # Secret to store ACME account key
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # HTTP-01 solver using Gateway API
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: eg
            namespace: default
            kind: Gateway
            group: gateway.networking.k8s.io

---
# Production ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for notifications
    email: ops@flow.swiss
    
    # Secret to store ACME account key
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # HTTP-01 solver using Gateway API
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: eg
            namespace: default
            kind: Gateway
            group: gateway.networking.k8s.io
